services:
  - type: web
    name: e-learn-platform
    env: node
    buildCommand: node build-production.js
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
    plan: free
    rootDir: .
    autoDeploy: true
    region: oregon
