services:
  - type: web
    name: e-learn-platform
    env: node
    buildCommand: npm ci && npm ci --include=dev --prefix client && npm ci --prefix server && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: PORT
        value: 10000
        
