services:
  - type: web
    name: lms-platform-client
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        status: 200
    headers:
      - key: Cache-Control
        value: "public, max-age=0, must-revalidate"
      - key: X-Frame-Options
        value: "DENY"
      - key: X-Content-Type-Options
        value: "nosniff"
